name: clean_architecture
description: a flutter clean architecture example project

publish_to: 'none'

version: 1.0.1+1

# flutter packages
# $flutter pub run build_runner build --delete-conflicting-outputs

# freezed 및 다른 auto generator 를 가진 패키지들이 제대로 빌드되지 않던 이슈가 있었음.authors:
# 4시간 이상을 굴러 봤지만 해결하지 못했고, photo class 의 이름을 다른 이름으로 바꾸면서 다시 빌드가 되었고,
# 그렇게 해서 해결 함.

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  provider: ^6.0.2

  # Json 모델 클래스를 정의하는 패키지.
  json_annotation: ^4.5.0

  # hashcode 및 == 를 간단하게 사용할 수 있게 해주는 패키지.
#  equatable: ^2.0.3

  #
  freezed_annotation: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  mockito: ^5.1.0
  build_runner: ^2.1.8
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true