name: clean_architecture
description: a flutter clean architecture example project

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  provider: ^6.0.2

  # Json 모델 클래스를
  json_annotation: ^4.5.0

  # hashcode 및 == 를 간단하게 사용할 수 있게 해주는 패키지.
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  mockito: ^5.1.0
  build_runner: ^2.1.8
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true